categories:
  Secrets:
    label: 'Secrets'

settings:
  plugin.tx_secrets.view.templateRootPath:
    label: 'Path to template root (FE)'
    default: 'EXT:secrets/Resources/Private/Templates/'
    type: string
    category: Secrets
  plugin.tx_secrets.view.partialRootPath:
    label: 'Path to template partials (FE)'
    default: 'EXT:secrets/Resources/Private/Partials/'
    type: string
    category: Secrets
  plugin.tx_secrets.view.layoutRootPath:
    label: 'Path to template layouts (FE)'
    default: 'EXT:secrets/Resources/Private/Layouts/'
    type: string
    category: Secrets
  plugin.tx_secrets.settings.secretkey:
    label: 'Secret key'
    default: 'QGWVZYJJCrnm2JM4bNhX'
    type: string
    category: Secrets
  plugin.tx_secrets.settings.showPid:
    label: 'PID Show Secret'
    default: '1'
    type: string
    category: Secrets
  plugin.tx_secrets.settings.createPid:
    label: 'PID Create Secret'
    default: '1'
    type: string
    category: Secrets
  plugin.tx_secrets.persistence.storagePid:
    label: 'Default storage PID'
    default: ''
    type: string
    category: Secrets